
addons:
  postgresql: "9.3"

before_script:
  - mysql -e 'create database search_cop;'
  - psql -c 'create database search_cop;' -U postgres

rvm:
  - 2.1.10
  - 2.3.1
  - 2.4.0
  - rbx-2
  - jruby
env:
  - DATABASE=sqlite
  - DATABASE=mysql
  - DATABASE=postgres
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

install:
  - "travis_retry bundle install"

script: "bundle exec rake test"
sudo: false

