
addons:
  postgresql: "9.6"

before_script:
  - mysql -e 'create database search_cop;'
  - psql -c 'create database search_cop;' -U postgres

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - rbx-3
  - jruby
env:
  - DATABASE=sqlite
  - DATABASE=mysql
  - DATABASE=postgres
matrix:
  include:
    - rvm: 2.4.1
      gemfile: gemfiles/5.0-Gemfile
      env: DATABASE=sqlite
    - rvm: 2.4.1
      gemfile: gemfiles/5.0-Gemfile
      env: DATABASE=mysql
    - rvm: 2.4.1
      gemfile: gemfiles/5.0-Gemfile
      env: DATABASE=postgres
  allow_failures:
    - rvm: rbx-3
    - rvm: jruby

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

install:
  - "travis_retry bundle install"

script: "bundle exec rake test"
sudo: false

